M48
; DRILL file {KiCad 7.0.7} date Sat Dec 16 14:30:28 2023
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-12-16T14:30:28-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.250
%
G90
G05
T1
X98760Y-144018
T2
X81560Y-66135
X81600Y-145015
X153940Y-66125
X153950Y-145035
T3
X132960Y-141868
X144390Y-141868
T0
M30
